inputs_def:
  - handle: ffmpeg_source
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
outputs_def:
  - handle: ffmpeg_only_video
    description: Output
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
  - handle: ffmpeg_only_audio
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
icon: ":fa6-solid:code-branch:currentColor:"
ui:
  default_width: 350
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
