inputs_def:
  - handle: ffmpeg_video
    json_schema:
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      contentMediaType: oomol/var
  - handle: audio_address
    json_schema:
      type: string
      ui:widget: file
  - handle: merge_file
    json_schema:
      type: string
      ui:widget: dir
  - handle: name
    json_schema:
      type: string
outputs_def:
  - handle: source_address
    description: Output
    json_schema:
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
icon: ":fa6-solid:code-pull-request:currentColor:"
ui:
  default_width: 350
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
